linters-settings:
  lll:
    line-length: 79
    tab-width: 4

  # varnamelen:
  #     ignore-decls:
  #       #- i int
  #       #- mi int
  #       #- ok bool

linters:
  enable-all: true
  disable:
    - cyclop
    - dupl
    - gocognit
    - gofumpt
    - lll
    - nlreturn
    - revive
    - varnamelen
    - wsl

    - deadcode # Deprecated
    - exhaustivestruct # Deprecated
    - golint # Deprecated
    - ifshort # Deprecated
    - interfacer # Deprecated
    - maligned # Deprecated
    - nosnakecase # Deprecated
    - scopelint # Deprecated
    - structcheck # Deprecated
    - varcheck # Deprecated

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go  # Exclude on test files.
      linters:
        - cyclop
        - dupl
        - forbidigo
        - funlen
        - gocognit
        - goconst
        - gocyclo
        - goerr113
        - gofumpt
        - lll
        - maintidx
        - nlreturn
        - nolintlint
        - paralleltest
        - revive
        - stylecheck
        - testpackage
        - thelper
        - unparam
        - varnamelen
        - wsl

run:
  timeout: 5m
  issues-exit-code: 2
  go: '1.22'
