// Package example shows various test options.
package example

import (
	"io"
)

func closeFile(r io.Closer) error {
	// This example will attempt to close the closer returning any error
	// generated by the close action.

	return r.Close()
}
